### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by ian-from-dover** [AY2122S2-CS2103T-T11-4/tp#107]
- [x] open in browser button is ugly no CSS applied 
- [x] put gifs onto README
- [x] icon to 64 and fxml to scale it down themselves
- [x] sidebar not updating the selected 
- [x] make computer use included inter font
